テーマのロゴの表示方法を変えました
concrnt/concrnt-world pull request #457
Opened 2024-01-09 15:04 UTC by Hennnatori

テーマのAppBar Styleにtransparentが設定されている場合にロゴのbackgrowndの色をbackground.paperの色を設定し透過しているよう見えるようにしました。

2024-01-09 15:07 UTC, totegamma requested changes
ありがとうございます！

こちらなのですが個人的には円形の背景は残したいので、backgroundの色はそのままで、
concurrentLogoのlowerColorとframeColorを、background.defulatにするかprimary.mainのほうにするかで切り替えるというのでどうでしょうか！

2024-01-09 15:09 UTC, totegamma requested changes
ありがとうございます！1点スタイル面であまり認識合わせできてなくて申し訳なかったのですがコメント入れたので見てもらえると嬉しいです...! 🙇🙇🙇

2024-01-09 15:09 UTC, totegamma commented on src/components/ThemeCard.tsx
> -                        background: theme.palette.primary.contrastText
ありがとうございます！

こちらなのですが個人的には円形の背景は残したいので、backgroundの色はそのままで、
concurrentLogoのlowerColorとframeColorを、background.defulatにするかprimary.mainのほうにするかで切り替えるというのでどうでしょうか！

2024-01-09 15:42 UTC, Hennnatori commented
こちらこそツートーンの意図を汲めなくて申し訳ないです
transparentという言葉で勘違いしてしまいました

修正しました～

2024-01-11 12:56 UTC, totegamma approved these changes
ありがとうございます！！！！！！

2024-01-11 12:56 UTC, merged